CLAUSE_TITLES = {
    "1.0": "Introduction",
    "2.0": "Raising of Indents",
    "2.2": "For Purchase of Materials",
    "2.3": "For Job/Service Contracts",
    "2.4": "Estimated Value",
    "3.0": "Scrutiny of Indents/Proposals",
    "4.0": "Action on Indent by MM Dept./Contract Cell/Contracting Department",
    "5.0": "Mode of Tendering",
    "5.2": "Open Tender/ Global Tender",
    "5.3": "Limited Tender Enquiry",
    "5.4": "Single Tender Enquiry",
    "5.4.1": "Single Tender Proprietary (STP) Enquiry",
    "5.4.2": "Single Tender Non-Proprietary (STNP) Enquiry",
    "5.5": "Repeat Orders",
    "5.6": "Rate Contract (Own)",
    "5.7": "Procurement on GeM",
    "5.8": "Emergency Purchase/Job Contract",
    "6.0": "Invitation to Tender",
    "6.14": "Consideration of Agents",
    "6.15": "Integrity Pact",
    "6.16": "Tender Documents",
    "6.17": "Methods for Calling of Tenders",
    "6.18": "Expression of Interest",
    "6.19": "Pre Bid Discussions / Meetings",
    "6.20": "Constitution of Tender Committee",
    "7.0": "Receipt and Opening of Offers",
    "7.29": "Return of Unopened Price Bids",
    "8.0": "Earnest Money Deposit (EMD)",
    "8.3": "Acceptable Modes of EMD / SD / PG",
    "8.4": "Return of Earnest Money Deposit",
    "9.0": "Scrutiny of Quotations",
    "9.1": "Single Part Quotations",
    "9.2": "2/3 Part Quotations",
    "9.4": "Opening of Price Bids",
    "9.5": "Comparative Statement of Price Bids",
    "10.0": "Purchase/Contract Proposal",
    "11.0": "Price Negotiations",
    "12.0": "Trial Purchase/Work Order",
    "13.0": "Issue of Order for Purchase/Job Contract",
    "13.7": "Posting of Contract Details",
    "14.0": "Extension of Delivery/Contract Period and Liquidated Damages",
    "15.0": "Amendments to Purchase/Contract Order",
    "16.0": "Payment Terms",
    "17.0": "Taxes",
    "18.0": "Cancellation of Purchase Order / Contract and Risk Purchase",
    "19.0": "Vendor Development",
    "20.0": "Closure of Contract",
    "21.0": "Price Discovery through Reverse Auction (RA)",
    "22.0": "Banning of Suppliers / Contractors",
    "23.0": "Procedure for Small Value Purchases of Materials",
    "24.0": "Procedure for Small Value Job/Service Contracts",
    "25.0": "General"
}
